apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-veloz-config
data:
  PEDIDOS_URL: "http://pedidos-service:80"
  PAGAMENTOS_URL: "http://pagamentos-service:80"
  ESTOQUE_URL: "http://estoque-service:80"
