apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      containers:
      - name: pagamentos
        image: lojaveloz/pagamentos:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        securityContext:
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: pagamentos-service
spec:
  selector:
    app: pagamentos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
