apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
  labels:
    app: pedidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      containers:
      - name: pedidos
        image: lojaveloz/pedidos:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: loja-veloz-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
        securityContext:
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: pedidos-service
spec:
  selector:
    app: pedidos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
